# Generated by Django 4.2.27 on 2026-03-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_corevalue_impact_missionvision_ourstory_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='image',
        ),
    ]
